# Some of this (well most) is copied from https://github.com/scikit-hep/pyhf/blob/4ecbf49/.github/workflows/docker.yml
name: Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  docker:
    name: Build, test, and publish Docker images to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository_owner }}/actions-runner

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Load current versions
        id: versions
        uses: falti/dotenv-action@v1.1.4
        with:
          log-variables: true
          export-variables: true
          keys-case: "upper"

      - name: Prepare
        id: prep
        run: |
          if [[ $GITHUB_REF == refs/pull/* ]]; then
            VERSION=pr-${{ github.event.number }}
          else
            VERSION=latest
          fi
          TAGS="${{ env.IMAGE_NAME }}:${VERSION},${{ env.IMAGE_NAME }}:latest,${{ env.IMAGE_NAME }}:sha-${GITHUB_SHA::8}"
          TAGS="$TAGS,${{ env.IMAGE_NAME }}:${{ env.RUNNER_VERSION }}-latest,${{ env.IMAGE_NAME }}:${{ env.RUNNER_VERSION }}-${{ env.RUNNER_CONTAINER_HOOKS_VERSION }}"
          TAGS="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION}"
          TAGS="$TAGS,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:sha-${GITHUB_SHA::8}"
          TAGS="$TAGS,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.RUNNER_VERSION }}-latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.RUNNER_VERSION }}-${{ env.RUNNER_CONTAINER_HOOKS_VERSION }}"
          echo "steps.prep.outputs.version=${VERSION}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "steps.prep.outputs.tags=${TAGS}"
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
          echo "steps.prep.outputs.created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          echo "created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to CERN GitLab
        if:
          github.event_name != 'pull_request' && github.repository ==
          'usatlas/runner'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
          password: ${{ secrets.GITLAB_REGISTRY_TOKEN }}

      - name: Login to GitHub Container Registry
        if:
          github.event_name != 'pull_request' && github.repository ==
          'usatlas/runner'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Test build
        id: build-only
        uses: docker/build-push-action@v6
        with:
          context: .
          file: images/Dockerfile
          tags: ${{ steps.prep.outputs.tags }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
          build-args: |
            RUNNER_VERSION=${{ env.RUNNER_VERSION }}
            RUNNER_CONTAINER_HOOKS_VERSION=${{ env.RUNNER_CONTAINER_HOOKS_VERSION }}
          load: true
          push: false

      - name: Image digest
        run: echo ${{ steps.build-only.outputs.digest }}

      - name: List built images
        run: docker images

      - name: Generate attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.build-only.outputs.digest }}
          push-to-registry: false

      - name: Build and publish to registry
        # every PR will trigger a push event on main, so check the push event is actually coming from main
        if:
          github.event_name == 'push' && github.ref == 'refs/heads/main' &&
          github.repository == 'usatlas/runner'
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: images/Dockerfile
          tags: ${{ steps.prep.outputs.tags }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
          build-args: |
            RUNNER_VERSION=${{ env.RUNNER_VERSION }}
            RUNNER_CONTAINER_HOOKS_VERSION=${{ env.RUNNER_CONTAINER_HOOKS_VERSION }}
          push: true
          platforms: linux/amd64,linux/arm64

      - name: Generate attestation
        # every PR will trigger a push event on main, so check the push event is actually coming from main
        if:
          github.event_name == 'push' && github.ref == 'refs/heads/main' &&
          github.repository == 'usatlas/runner'
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.build-and-push.outputs.digest }}
          push-to-registry: true
